name: BoLTestPlugin
main: com.bol.BoLTestPlugin
authors: [Scyntrus]
version: 0.0.1
depends:
commands:
    soulbind:
        description: Make an item soulbound
        usage: "/soulbind"
permissions:
